travis:
  secure:
    BINSTAR_TOKEN: iUm9JvXftE1gAryLXowb1Ca9N45IcIYjND5FdUTBHcRLjj53vXAj6nLvEHROou44C/larXbZb2e4VgDID1PWgt4CHxggWWarj4kbshlvsXXhGRczhFeI5Gl1iEDhYXoSqvekqOrtITlSmCk8GwcoB1ssgn+NwE99kadK3GoPak9Yi8milg0bm1819PFFTDuntuKRD7YEsK9RYJHFzELmnMeu9uqaRl/DH8GeKhFfLBqBR8sfsAJbX6LYNtm2y1cAf0IBXAO3OpS1zpUZT0WCmxcbkbMO11uAwC7NqCdGgJ4DUjR8MGIU2QX3puCh7uYnjJl7teoaM2aq+txYAwkPV/fAYBKjLiz+7nJmcuaBfXu/zO5xRvz31hcKXJeGGEcdQY0EF/LP9woJY6Hv9broK+bYkbG46K5oYQ4KZb0VZ4lZ1/2Y5cS94zCxqHhOtRFNtRP9p6DqUx8UFc5aRekc6AMOKPbZW5tMi2D8gBZLXbERFjebps21KbXzDDiw+hAjqjZmj6YkHdQSBQEYhEOx6bVql6fB8NcCprGA1D9Q3yUNLiG05bN2Fm5JNysgdzK1WcyRnHS8iiny6YnTBHJBymNrs0XmFVwfDt0WFt8YY8x51askk6XgPiZwGFxDJWyAZq/2OvF0hsxo7pW8NWawFLsUuEO7HF0fsdt5WJkL2cM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
