travis:
  secure:
    BINSTAR_TOKEN: XNgmPU69IowuqeQdqnPodWDRMfdRSx7QAL4RhsrXCfDaxEAFSxmDGa/JDOXnE0SzyqcS92QjoFLuzIUpa97NSCmXfifhepC+WQPUNh/tuR7ec34AMR2MaG7Ri/ZRRHZYubBttwWg5BbLXNQN5De/d1LKnKdKr+cIEv2cYM/unrB+2cZJpvh/ci843SSudQ3xZdVDAJv8ROX4M++Wa5Z53bVuzl6o9LDp1AlxkHTve3xQgQRB+rzD+iG5qYxvRtb1Z2slGzP2xiwz2XBm46GAwXYfEDvaWoj4uukPspjJY7QAmc7GoyYadtJ/vB+nr5gsuGyu5T1AlG2a8kFwfLr9UZwPVbE8IvBpyIKl00JxMowMH2dCX5NfUIYkNCthSbKhd3PeztEzItvaQxhEOhpB4ncxKJASODC2O2bhqAjWA13dzGIOPNUlcqqzshZCrL5bQeUHhEZ/1gOdIES8u3UPDJspM7cJ7aFGoeUnzCZLQxNNj1B3/Bj+FKdipGA7+yuhzGBg7SpEuv/fLVmtwlrAnM1Ex7C1L6Va/lykG7/NRZhWKnonBJHTzMKiUmzu37Wv6oWZbjazxVC4ymeuL6We7tujMfO41BFq8qEbt18XsEj+0sNmEzObXBgN6HoY3Z3+b+Yom1XYSITunGkF/MkH5Zz2zXnNULBNRwXFe7ekIzw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
